module.exports = {
  _: {
    full: "100%",
    half: "50%",
    fullvw: "100vw",
    fullvh: "100vh",
    "1px": "1px",
    auto: "auto",
  },
  "text-w": {},
  "text-ls": {},
  "text-lh": {},
  "text-s": {
    italic: "",
    normal: "",
  },
  "text-a": {
    center: "",
    left: "",
    right: "",
    justify: "",
    start: "",
    end: "",
  },
  "text-d": {
    underline: "",
    overline: "",
    "line-through": "",
    none: "",
  },
  "text-t": {
    uppercase: "",
    lowercase: "",
    capitalize: "",
    none: "",
  },
  "text-ws": {
    normal: "",
    nowrap: "",
    pre: "",
    "pre-wrap": "",
    "pre-line": "",
    "break-spaces": "",
  },
  "text-wb": {
    normal: "",
    words: "",
    all: "",
    keep: "",
  },
  "v-align": {
    baseline: "",
    top: "",
    middle: "",
    bottom: "",
    "text-top": "",
    "text-bottom": "",
    sub: "",
    super: "",
  },
  "list-style": {
    disc: "",
    square: "",
    decimal: "",
    none: "",
  },
  "list-style-p": {
    inside: "",
    outside: "",
  },
  "border-s": {
    solid: "",
    dashed: "",
    dotted: "",
    double: "",
    hidden: "",
  },
  "border-t-s": {
    solid: "",
    dashed: "",
    dotted: "",
    double: "",
    hidden: "",
  },
  "border-r-s": {
    solid: "",
    dashed: "",
    dotted: "",
    double: "",
    hidden: "",
  },
  "border-b-s": {
    solid: "",
    dashed: "",
    dotted: "",
    double: "",
    hidden: "",
  },
  "border-l-s": {
    solid: "",
    dashed: "",
    dotted: "",
    double: "",
    hidden: "",
  },
  "outline-s": {
    solid: "",
    dashed: "",
    dotted: "",
    double: "",
    groove: "",
    ridge: "",
    inset: "",
    outset: "",
  },
  order: {
    first: "-1",
    last: "99999",
    none: "0",
  },
  _i_rounded: {
    full: "999rem",
    none: "0",
  },
  d: {
    inline: "",
    block: "",
    contents: "",
    flex: "",
    grid: "",
    "inline-block": "",
    "inline-flex": "",
    "inline-grid": "",
    "inline-table	": "",
    "list-item": "",
    "run-in": "",
    table: "",
    "table-caption": "",
    "table-column-group": "",
    "table-header-group": "",
    "table-footer-group": "",
    "table-row-group": "",
    "table-cell": "",
    "table-column": "",
    "table-row": "",
    none: "",
  },
  p: {
    static: "",
    absolute: "",
    fixed: "",
    relative: "",
    sticky: "",
  },
  "bg-s": {
    auto: "",
    cover: "",
    contain: "",
  },
  "bg-p": {
    center: "",
    top: "",
    right: "",
    bottom: "",
    left: "",
    "top-right": "",
    "top-left": "",
    "bottom-right": "",
    "bottom-left": "",
  },
  "bg-o": {
    border: "",
    padding: "",
    content: "",
  },
  "bg-clip": {
    border: "",
    padding: "",
    content: "",
    text: "",
  },
  "bg-r": {
    repeat: "",
    "no-repeat": "",
    "repeat-x": "",
    "repeat-y": "",
  },
  "bg-a": {
    local: "",
    scroll: "",
    fixed: "",
  },
  "mix-blend": {
    normal: "",
    multiply: "",
    screen: "",
    lighten: "",
    darken: "",
    difference: "",
    "soft-light": "",
    "hard-light": "",
    "color-dodge": "",
    "color-burn": "",
    exclusion: "",
    hue: "",
    color: "",
    luminosity: "",
    "plus-lighter": "",
  },
  "bg-blend": {
    normal: "",
    multiply: "",
    screen: "",
    lighten: "",
    darken: "",
    difference: "",
    "soft-light": "",
    "hard-light": "",
    "color-dodge": "",
    "color-burn": "",
    exclusion: "",
    hue: "",
    color: "",
    luminosity: "",
    "plus-lighter": "",
  },
  "transform-o": {
    center: "",
    top: "",
    right: "",
    bottom: "",
    left: "",
    "top-right": "",
    "top-left": "",
    "bottom-right": "",
    "bottom-left": "",
  },
  z: {
    auto: "",
  },
  "flex-g": {
    0: "",
    1: "",
  },
  "flex-s": {
    0: "",
    1: "",
  },
  "j-content": {
    start: "",
    center: "",
    end: "",
    between: "",
    around: "",
    evenly: "",
    stretch: "",
    normal: "",
  },
  "j-items": {
    start: "",
    center: "",
    end: "",
    stretch: "",
  },
  "j-self": {
    start: "",
    center: "",
    end: "",
    stretch: "",
  },
  "a-content": {
    start: "",
    center: "",
    end: "",
    between: "",
    around: "",
    evenly: "",
    stretch: "",
    normal: "",
  },
  "a-items": {
    start: "",
    center: "",
    end: "",
    baseline: "",
    stretch: "",
  },
  "a-self": {
    start: "",
    center: "",
    end: "",
    baseline: "",
    auto: "",
    stretch: "",
  },
  "p-content": {
    start: "",
    center: "",
    end: "",
    between: "",
    around: "",
    evenly: "",
    stretch: "",
    normal: "",
  },
  "p-items": {
    start: "",
    center: "",
    end: "",
    stretch: "",
  },
  "p-self": {
    start: "",
    center: "",
    end: "",
    stretch: "",
  },
  "box-s": {
    border: "",
    content: "",
  },
  float: {
    none: "",
    left: "",
    right: "",
  },
  clear: {
    none: "",
    left: "",
    right: "",
    both: "",
  },
  "ts-f": {
    linear: "",
    ease: "",
    "ease-in": "",
    "ease-out": "",
    "cubic-bezier()": "",
  },
  "tsm-f": {
    linear: "",
    ease: "",
    "ease-in": "",
    "ease-out": "",
    "cubic-bezier()": "",
  },
  "ts-p": {
    color: "",
    "background-color": "",
    "border-color": "",
    "border-color": "",
    width: "",
    height: "",
    transform: "",
    filter: "",
  },
  "tsm-p": {
    color: "",
    "background-color": "",
    "border-color": "",
    "border-color": "",
    width: "",
    height: "",
    transform: "",
    filter: "",
  },
  animation: {
    spin: "",
    flare: "",
    pulse: "",
  },
  "user-select": {
    none: "",
    text: "",
    all: "",
    auto: "",
  },
  appearance: {
    none: "",
    auto: "",
  },
  cursor: {
    auto: "",
    default: "",
    wait: "",
    pointer: "",
    move: "",
    text: "",
    help: "",
    "not-allowed": "",
    "context-menu": "",
    progress: "",
    cell: "",
    crosshair: "",
    "vertical-text": "",
    alias: "",
    copy: "",
    "no-drop": "",
    grab: "",
    grabbing: "",
    "all-scroll": "",
    "col-resize": "",
    "row-resize": "",
    "n-resize": "",
    "e-resize": "",
    "s-resize": "",
    "w-resize": "",
    "ne-resize": "",
    "nw-resize": "",
    "se-resize": "",
    "sw-resize": "",
    "ew-resize": "",
    "ns-resize": "",
    "nesw-resize": "",
    "nwse-resize": "",
    "zoom-in": "",
    "zoom-out": "",
    none: "",
  },
  "pointer-e": {
    none: "",
    auto: "",
  },
  resize: {
    xy: "",
    x: "",
    y: "",
    none: "",
  },
  "obj-f": {
    none: "",
    cover: "",
    fill: "",
    contain: "",
    "scale-down": "",
  },
  "obj-p": {
    center: "",
    top: "",
    right: "",
    bottom: "",
    left: "",
    "top-right": "",
    "top-left": "",
    "bottom-right": "",
    "bottom-left": "",
  }
};
